# Generated by Django 4.1.2 on 2022-10-22 09:44

import admin_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dept_name",
                    models.CharField(
                        choices=[
                            ("CSE", "CSE"),
                            ("EEE", "EEE"),
                            ("SWE", "SWE"),
                            ("MCE", "ME"),
                            ("IPE", "IPE"),
                            ("CEE", "CEE"),
                            ("BTM", "BTM"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("name", models.CharField(max_length=256)),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="main.student",
                    ),
                ),
                ("student_ID", models.IntegerField(null=True, unique=True)),
                ("address", models.TextField()),
                ("father_name", models.CharField(max_length=256)),
                ("mother_name", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=15)),
                (
                    "semester",
                    models.IntegerField(
                        choices=[
                            (6, "6"),
                            (3, "3"),
                            (1, "1"),
                            (7, "7"),
                            (8, "8"),
                            (2, "2"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        default=1,
                    ),
                ),
                ("image", models.ImageField(upload_to=admin_app.models.filepath)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "FEMALE"), ("Male", "MALE")], max_length=30
                    ),
                ),
                ("date_of_birth", models.DateField(max_length=10, null=True)),
                ("session", models.DateField(max_length=10, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.department",
                    ),
                ),
            ],
        ),
    ]
