# Generated by Django 4.1.1 on 2022-10-11 18:40

import admin_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('admin_app', '0002_alter_department_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.student')),
                ('student_ID', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=256)),
                ('mother_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('semester', models.IntegerField(choices=[(2, '2'), (1, '1'), (5, '5'), (6, '6'), (3, '3'), (8, '8'), (7, '7'), (4, '4')], default=1)),
                ('image', models.ImageField(upload_to=admin_app.models.filepath)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=30)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('session', models.DateField(max_length=10)),
            ],
        ),
    ]
