# Generated by Django 4.1.1 on 2022-10-12 18:03

import admin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default='CSE', max_length=30, verbose_name=admin_app.models.department),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (1, '1'), (7, '7'), (2, '2'), (6, '6'), (5, '5'), (8, '8')], default=1),
        ),
    ]
