# Generated by Django 4.1.1 on 2022-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(8, '8'), (2, '2'), (6, '6'), (7, '7'), (4, '4'), (3, '3'), (5, '5'), (1, '1')], default=1),
        ),
    ]
