# Generated by Django 4.1.1 on 2022-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(8, '8'), (1, '1'), (6, '6'), (4, '4'), (7, '7'), (5, '5'), (2, '2'), (3, '3')], default=1),
        ),
    ]
