# Generated by Django 4.1.1 on 2022-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (6, '6'), (3, '3'), (7, '7'), (4, '4'), (8, '8'), (2, '2'), (5, '5')], default=1),
        ),
    ]
