# Generated by Django 4.1.1 on 2022-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(8, '8'), (2, '2'), (5, '5'), (6, '6'), (4, '4'), (7, '7'), (3, '3'), (1, '1')], default=1),
        ),
    ]
