# Generated by Django 4.1.1 on 2022-10-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(3, '3'), (8, '8'), (2, '2'), (7, '7'), (5, '5'), (6, '6'), (1, '1'), (4, '4')], default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_ID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
