# Generated by Django 4.1.1 on 2022-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_studentprofile_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(3, '3'), (7, '7'), (6, '6'), (5, '5'), (2, '2'), (1, '1'), (4, '4'), (8, '8')], default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='session',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
