# Generated by Django 4.1.1 on 2022-10-22 08:38

import admin_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('admin_app', '0019_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(8, '8'), (4, '4'), (7, '7'), (1, '1'), (3, '3'), (5, '5'), (2, '2'), (6, '6')], default=1),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.faculty')),
                ('address', models.TextField()),
                ('room', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to=admin_app.models.filepathFaculty)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=30)),
                ('date_of_birth', models.DateField(max_length=10, null=True)),
                ('education', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.department')),
            ],
        ),
    ]
