# Generated by Django 4.1.1 on 2022-10-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_deptheadfaculty_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptheadfaculty',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (1, '1'), (4, '4'), (2, '2'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
