# Generated by Django 4.1.1 on 2022-10-23 14:05

import admin_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('admin_app', '0026_alter_facultyprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMedProfile',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.staffmed')),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to=admin_app.models.filepathFaculty)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30)),
                ('duty', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(4, '4'), (2, '2'), (7, '7'), (8, '8'), (3, '3'), (6, '6'), (1, '1'), (5, '5')], default=1),
        ),
    ]
