# Generated by Django 4.1.1 on 2022-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_staffmedprofile_alter_facultyprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffmedprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (7, '7'), (5, '5'), (6, '6'), (4, '4'), (8, '8'), (2, '2')], default=1),
        ),
    ]
