# Generated by Django 4.1.1 on 2022-10-23 17:14

import admin_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('admin_app', '0029_staffmedprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLibProfile',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.stafflib')),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to=admin_app.models.filepathStaff)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30)),
                ('duty', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffmedprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (8, '8'), (5, '5'), (6, '6'), (4, '4'), (1, '1'), (7, '7')], default=1),
        ),
    ]
