# Generated by Django 4.1.1 on 2022-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='stafflibprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffmedprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
