# Generated by Django 4.1.1 on 2022-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_studentprofile_section_alter_facultyprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate  Professor'), ('Professor', 'Professor')], default='Lecturer', max_length=30),
        ),
    ]
