# Generated by Django 4.1.1 on 2022-10-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_studentprofile_cr_alter_deptheadfaculty_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('semester', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('dept_name', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('SWE', 'SWE'), ('MCE', 'ME'), ('IPE', 'IPE'), ('CEE', 'CEE'), ('BTM', 'BTM')], max_length=30)),
                ('faculty', models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='admin_app.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(choices=[(4.0, 'A+'), (3.75, 'A'), (3.5, 'A-'), (3.25, 'B+'), (3.0, 'B'), (2.75, 'B-'), (2.5, 'C+'), (2.25, 'C'), (2.0, 'D'), (0.0, 'F')])),
                ('date_joined', models.DateField(max_length=10, null=True)),
                ('date_finished', models.DateField(blank=True, max_length=10, null=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.courses')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(through='admin_app.Enrollment', to='admin_app.studentprofile'),
        ),
    ]
