# Generated by Django 4.1.1 on 2022-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_courses_enrollment_courses_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credit',
            field=models.FloatField(null=True),
        ),
    ]
