# Generated by Django 4.1.1 on 2022-10-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_alter_enrollment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('book_code', models.CharField(max_length=256)),
                ('rack_no', models.IntegerField(null=True)),
                ('category', models.CharField(blank=True, choices=[('MATH', 'MATH'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('HUMANITIES', 'HUMANITIES'), ('ELECTRICAL', 'ELECTRICAL'), ('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('MECHANICAL', 'MECHANIAL'), ('CIVIL', 'CIVIL'), ('INDUSTRIAL', 'INDUSTRIAL'), ('BUSINESS', 'BUSINESS'), ('MAANGEMENT', 'MANAGEMENT')], max_length=30, null=True)),
                ('borrow_date', models.DateField(blank=True, max_length=10, null=True)),
                ('due_date', models.DateField(blank=True, max_length=10, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.studentprofile')),
            ],
        ),
    ]
