# Generated by Django 4.1.1 on 2022-11-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_alter_books_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=256)),
                ('date', models.DateField(max_length=10, null=True)),
                ('remeration', models.IntegerField(null=True)),
                ('referred_by', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.studentprofile')),
            ],
        ),
    ]
