# Generated by Django 4.1.1 on 2022-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_rename_medlogs_medlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlog',
            name='remeration_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
