# Generated by Django 4.1.1 on 2022-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0046_alter_medlog_remuneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.department'),
        ),
    ]
