# Generated by Django 4.1.1 on 2022-11-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_remove_courses_dept_name_courses_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created_d_ID',
            field=models.IntegerField(null=True),
        ),
    ]
