# Generated by Django 4.1.1 on 2022-11-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0048_courses_created_d_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.courses')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.facultyprofile')),
            ],
        ),
    ]
