# Generated by Django 4.1.1 on 2022-11-22 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
