# Generated by Django 4.1.1 on 2022-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0051_notice_date_alter_notice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='update_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
