# Generated by Django 4.1.1 on 2022-11-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0052_notice_update_notice_update_date_notice_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='acdemic_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('update', models.BooleanField(default=False)),
                ('update_time', models.TimeField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.studentprofile')),
            ],
        ),
    ]
