# Generated by Django 4.1.1 on 2022-11-22 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0054_rename_acdemic_notice_student_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notice',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
