# Generated by Django 4.1.1 on 2022-11-22 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0055_student_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notice',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
