# Generated by Django 4.1.1 on 2022-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0056_student_notice_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='designation_hier',
            field=models.IntegerField(default=1),
        ),
    ]
