# Generated by Django 4.1.1 on 2022-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0057_facultyprofile_designation_hier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
