# Generated by Django 4.1.1 on 2022-10-29 11:28

from django.db import migrations, models
import main.admision_models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_questionbank_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer')], default='Winter', max_length=30)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('SWE', 'SWE'), ('MCE', 'ME'), ('IPE', 'IPE'), ('CEE', 'CEE'), ('BTM', 'BTM')], max_length=30)),
                ('file', models.FileField(upload_to=main.models.path_SemesterQ)),
            ],
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='file',
            field=models.FileField(upload_to=main.admision_models.path_admissionQ),
        ),
    ]
